use std::{
    env, fs, io,
    path::{Path, PathBuf},
};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let prompts_dir = manifest_dir.join("prompts");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let generated_path = out_dir.join("prompts.rs");

    println!("cargo:rerun-if-changed={}", prompts_dir.display());

    let prompts = match collect_prompts(&prompts_dir) {
        Ok(prompts) => prompts,
        Err(error) => {
            println!("cargo:error=failed to collect prompts: {error}");
            std::process::exit(1);
        }
    };

    let generated = match generate_prompts(&prompts) {
        Ok(generated) => generated,
        Err(error) => {
            println!("cargo:error=failed to generate prompt constants: {error}");
            std::process::exit(1);
        }
    };

    fs::write(&generated_path, generated).unwrap_or_else(|error| {
        panic!(
            "failed to write generated prompts to {}: {error}",
            generated_path.display()
        )
    });
}

fn collect_prompts(prompts_dir: &Path) -> io::Result<Vec<PromptFile>> {
    if !prompts_dir.exists() {
        return Ok(Vec::new());
    }

    let mut prompts = Vec::new();
    collect_prompt_files(prompts_dir, prompts_dir, &mut prompts)?;
    prompts.sort_by(|left, right| left.relative_path.cmp(&right.relative_path));

    Ok(prompts)
}

fn collect_prompt_files(
    root: &Path,
    current: &Path,
    prompts: &mut Vec<PromptFile>,
) -> io::Result<()> {
    for entry in fs::read_dir(current)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;

        if file_type.is_dir() {
            collect_prompt_files(root, &path, prompts)?;
        } else if file_type.is_file() {
            println!("cargo:rerun-if-changed={}", path.display());

            let relative_path = path
                .strip_prefix(root)
                .expect("prompt path should be under prompts root")
                .to_path_buf();
            let content = fs::read_to_string(&path)?;

            prompts.push(PromptFile {
                relative_path,
                content,
            });
        }
    }

    Ok(())
}

fn generate_prompts(prompts: &[PromptFile]) -> Result<String, String> {
    let mut generated = String::from("// This file is @generated by build.rs.\n\n");
    let mut names = std::collections::BTreeSet::new();
    let mut prompt_entries = Vec::new();

    for prompt in prompts {
        let const_name = const_name_from_path(&prompt.relative_path)?;

        if !names.insert(const_name.clone()) {
            return Err(format!(
                "duplicate prompt constant `{const_name}` generated from {}",
                prompt.relative_path.display()
            ));
        }

        generated.push_str(&format!(
            "pub const {const_name}: &str = {content:?};\n",
            content = prompt.content
        ));
        prompt_entries.push((
            prompt.relative_path.to_string_lossy().replace('\\', "/"),
            const_name,
        ));
    }

    generated.push_str("\npub const PROMPTS: &[(&str, &str)] = &[\n");
    for (relative_path, const_name) in prompt_entries {
        generated.push_str(&format!("    ({relative_path:?}, {const_name}),\n"));
    }
    generated.push_str("];\n");

    Ok(generated)
}

fn const_name_from_path(path: &Path) -> Result<String, String> {
    let mut parts = Vec::new();
    let mut components = path.components().peekable();

    while let Some(component) = components.next() {
        let is_file_name = components.peek().is_none();
        let component = component.as_os_str().to_string_lossy();
        let name = if is_file_name {
            let component = Path::new(component.as_ref());
            component
                .file_stem()
                .or_else(|| component.file_name())
                .map(|value| value.to_string_lossy())
                .ok_or_else(|| format!("invalid prompt path component in {}", path.display()))?
        } else {
            component
        };

        parts.push(sanitize_identifier_part(&name));
    }

    let mut name = parts.join("_");
    while name.contains("__") {
        name = name.replace("__", "_");
    }
    name = name.trim_matches('_').to_string();

    if name.is_empty() {
        return Err(format!(
            "prompt path {} does not produce a valid constant name",
            path.display()
        ));
    }

    if name
        .chars()
        .next()
        .is_some_and(|character| character.is_ascii_digit())
    {
        name.insert(0, '_');
    }

    Ok(name.to_ascii_uppercase())
}

fn sanitize_identifier_part(value: &str) -> String {
    value
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() {
                character
            } else {
                '_'
            }
        })
        .collect()
}

struct PromptFile {
    relative_path: PathBuf,
    content: String,
}
